version: "3.8"
services: 
 mongodb:
  image: mongo
  container_name: mongodb
  environment:
   - MONGO_INITDB_DATABASE:dactilocontest
  volumes:
   - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro
  ports:
   - 27017:27017
  restart: unless-stopped
 app:
  build: ./DactiloConstest
  container_name: dactilo-container
  ports:
   - 3000:3000
  restart: unless-stopped
 mongo-seed:
  build: ./seed
  links:
   - mongodb
